apiVersion: apps/v1
kind: Deployment
metadata:
  labels :
    app: mysql
  name: mysql
  namespace: webapplication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysqldb
        image: 527426504908.dkr.ecr.us-east-1.amazonaws.com/assignment1db:v1.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value : prince
        ports: 
        - containerPort: 3306
          protocol: TC
