apiVersion: v1
kind: Pod
metadata:
  labels: 
    app: mysql
  name: mysql
  namespace:  webapplication
spec:
  containers:
  - name: mysqldb
    image: 527426504908.dkr.ecr.us-east-1.amazonaws.com/assignment1db:v1.0
    ports: 
    - containerPort: 3306
      protocol: TCP
    env:
    - name: MYSQL_ROOT_PASSWORD
      value : prince